fiware-skuld-three-glances:
  image: fiware-skuld-three-glances 
  environment: 
   - OS_AUTH_URL
   - OS_USERNAME
   - OS_TENANT_NAME
   - OS_PASSWORD
   - OS_REGION_NAME
   - OS_PROJECT_DOMAIN_NAME
   - OS_USER_DOMAIN_NAME
   - BOOKED_IP1
   - BOOKED_IP2
   - Region1
   - Region2
   - Region3
